// Get all profiles
export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';
export const PROFILE_RESET = 'PROFILE_RESET';

// Get all profiles as ADMIN
export const PROFILE_ADMIN_REQUEST = 'PROFILE_ADMIN_REQUEST';
export const PROFILE_ADMIN_SUCCESS = 'PROFILE_ADMIN_SUCCESS';
export const PROFILE_ADMIN_FAILURE = 'PROFILE_ADMIN_FAILURE';
export const PROFILE_ADMIN_RESET = 'PROFILE_ADMIN_RESET';

// Get Single full-Profile by ID
export const PROFILE_BY_ID_REQUEST = 'PROFILE_BY_ID_REQUEST';
export const PROFILE_BY_ID_SUCCESS = 'PROFILE_BY_ID_SUCCESS';
export const PROFILE_BY_ID_FAILURE = 'PROFILE_BY_ID_FAILURE';
export const PROFILE_BY_ID_RESET = 'PROFILE_BY_ID_RESET';

// Get a single profile if logged in user
export const PROFILE_OF_LOGGED_IN_USER_REQUEST =
  'PROFILE_OF_LOGGED_IN_USER_REQUEST';
export const PROFILE_OF_LOGGED_IN_USER_SUCCESS =
  'PROFILE_OF_LOGGED_IN_USER_SUCCESS';
export const PROFILE_OF_LOGGED_IN_USER_FAILURE =
  'PROFILE_OF_LOGGED_IN_USER_FAILURE';
export const PROFILE_OF_LOGGED_IN_USER_RESET =
  'PROFILE_OF_LOGGED_IN_USER_RESET';

// Create a sample profile
export const PROFILE_CREATE_REQUEST = 'PROFILE_CREATE_REQUEST';
export const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS';
export const PROFILE_CREATE_FAILURE = 'PROFILE_CREATE_FAILURE';
export const PROFILE_CREATE_RESET = 'PROFILE_CREATE_RESET';

// Update(edit) PROFILE DATA
export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILURE = 'PROFILE_UPDATE_FAILURE';
export const PROFILE_UPDATE_RESET = 'PROFILE_UPDATE_RESET';

//Delete profile
export const PROFILE_DELETE_REQUEST = 'PROFILE_DELETE_REQUEST';
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS';
export const PROFILE_DELETE_FAILURE = 'PROFILE_DELETE_FAILURE';

//Delete a single review
export const PROFILE_DELETE_REVIEW_REQUEST = 'PROFILE_DELETE_REVIEW_REQUEST';
export const PROFILE_DELETE_REVIEW_SUCCESS = 'PROFILE_DELETE_REVIEW_SUCCESS';
export const PROFILE_DELETE_REVIEW_FAILURE = 'PROFILE_DELETE_REVIEW_FAILURE';

//Delete profile
export const PROFILE_VERIFY_QUALIFICATION_REQUEST =
  'PROFILE_VERIFY_QUALIFICATION_REQUEST';
export const PROFILE_VERIFY_QUALIFICATION_SUCCESS =
  'PROFILE_VERIFY_QUALIFICATION_SUCCESS';
export const PROFILE_VERIFY_QUALIFICATION_FAILURE =
  'PROFILE_VERIFY_QUALIFICATION_FAILURE';

// Profile click counter
export const PROFILE_CLICK_COUNTER_REQUEST = 'PROFILE_CLICK_COUNTER_REQUEST';
export const PROFILE_CLICK_COUNTER_SUCCESS = 'PROFILE_CLICK_COUNTER_SUCCESS';
export const PROFILE_CLICK_COUNTER_FAILURE = 'PROFILE_CLICK_COUNTER_FAILURE';

// Get Profile Images for ProfileImage model
export const PROFILE_IMAGES_REQUEST = 'PROFILE_IMAGES_REQUEST';
export const PROFILE_IMAGES_SUCCESS = 'PROFILE_IMAGES_SUCCESS';
export const PROFILE_IMAGES_FAILURE = 'PROFILE_IMAGES_FAILURE';
export const PROFILE_IMAGES_RESET = 'PROFILE_IMAGES_RESET';

// Get Profile Images for ProfileImage model 'PUBLIC
export const PROFILE_IMAGES_PUBLIC_REQUEST = 'PROFILE_IMAGES_PUBLIC_REQUEST';
export const PROFILE_IMAGES__PUBLIC_SUCCESS = 'PROFILE_IMAGES__PUBLIC_SUCCESS';
export const PROFILE_IMAGES__PUBLIC_FAILURE = 'PROFILE_IMAGES__PUBLIC_FAILURE';
