export const QUALIFICATION_DOCUMENT_LIST_REQUEST =
  'QUALIFICATION_DOCUMENT_LIST_REQUEST';
export const QUALIFICATION_DOCUMENT_LIST_SUCCESS =
  'QUALIFICATION_DOCUMENT_LIST_SUCCESS';
export const QUALIFICATION_DOCUMENT_LIST_FAILURE =
  'QUALIFICATION_DOCUMENT_LIST_FAILURE';
export const QUALIFICATION_DOCUMENT_LIST_RESET =
  'QUALIFICATION_DOCUMENT_LIST_RESET';

export const QUALIFICATION_DOCUMENT_UPLOAD_REQUEST =
  'QUALIFICATION_DOCUMENT_UPLOAD_REQUEST';
export const QUALIFICATION_DOCUMENT_UPLOAD_SUCCESS =
  'QUALIFICATION_DOCUMENT_UPLOAD_SUCCESS';
export const QUALIFICATION_DOCUMENT_UPLOAD_FAILURE =
  'QUALIFICATION_DOCUMENT_UPLOAD_FAILURE';
export const QUALIFICATION_DOCUMENT_UPLOAD_RESET =
  'QUALIFICATION_DOCUMENT_UPLOAD_RESET';

export const QUALIFICATION_DOCUMENT_REPLACE_REQUEST =
  'QUALIFICATION_DOCUMENT_REPLACE_REQUEST';
export const QUALIFICATION_DOCUMENT_REPLACE_SUCCESS =
  'QUALIFICATION_DOCUMENT_REPLACE_SUCCESS';
export const QUALIFICATION_DOCUMENT_REPLACE_FAILURE =
  'QUALIFICATION_DOCUMENT_REPLACE_FAILURE';
export const QUALIFICATION_DOCUMENT_REPLACE_RESET =
  'QUALIFICATION_DOCUMENT_REPLACE_RESET';

export const QUALIFICATION_DOCUMENT_DELETE_REQUEST =
  'QUALIFICATION_DOCUMENT_DELETE_REQUEST';
export const QUALIFICATION_DOCUMENT_DELETE_SUCCESS =
  'QUALIFICATION_DOCUMENT_DELETE_SUCCESS';
export const QUALIFICATION_DOCUMENT_DELETE_FAILURE =
  'QUALIFICATION_DOCUMENT_DELETE_FAILURE';
export const QUALIFICATION_DOCUMENT_DELETE_RESET =
  'QUALIFICATION_DOCUMENT_DELETE_RESET';

export const QUALIFICATION_DOCUMENT_ADMIN_LIST_REQUEST =
  'QUALIFICATION_DOCUMENT_ADMIN_LIST_REQUEST';
export const QUALIFICATION_DOCUMENT_ADMIN_LIST_SUCCESS =
  'QUALIFICATION_DOCUMENT_ADMIN_LIST_SUCCESS';
export const QUALIFICATION_DOCUMENT_ADMIN_LIST_FAILURE =
  'QUALIFICATION_DOCUMENT_ADMIN_LIST_FAILURE';
export const QUALIFICATION_DOCUMENT_ADMIN_LIST_RESET =
  'QUALIFICATION_DOCUMENT_ADMIN_LIST_RESET';

export const QUALIFICATION_DOCUMENT_REVIEW_REQUEST =
  'QUALIFICATION_DOCUMENT_REVIEW_REQUEST';
export const QUALIFICATION_DOCUMENT_REVIEW_SUCCESS =
  'QUALIFICATION_DOCUMENT_REVIEW_SUCCESS';
export const QUALIFICATION_DOCUMENT_REVIEW_FAILURE =
  'QUALIFICATION_DOCUMENT_REVIEW_FAILURE';
export const QUALIFICATION_DOCUMENT_REVIEW_RESET =
  'QUALIFICATION_DOCUMENT_REVIEW_RESET';
