export const STRIPE_CHECKOUT_REQUEST = 'STRIPE_CHECKOUT_REQUEST';
export const STRIPE_CHECKOUT_SUCCESS = 'STRIPE_CHECKOUT_SUCCESS';
export const STRIPE_CHECKOUT_FAILURE = 'STRIPE_CHECKOUT_FAILURE';

export const STRIPE_SUBSCRIPTION_REQUEST = 'STRIPE_SUBSCRIPTION_REQUEST';
export const STRIPE_SUBSCRIPTION_SUCCESS = 'STRIPE_SUBSCRIPTION_SUCCESS';
export const STRIPE_SUBSCRIPTION_FAILURE = 'STRIPE_SUBSCRIPTION_FAILURE';

export const STRIPE_PAYMENT_CONFIRMATION_REQUEST = 'STRIPE_PAYMENT_CONFIRMATION_REQUEST';
export const STRIPE_PAYMENT_CONFIRMATION_SUCCESS = 'STRIPE_PAYMENT_CONFIRMATION_SUCCESS';
export const STRIPE_PAYMENT_CONFIRMATION_FAILURE = 'STRIPE_PAYMENT_CONFIRMATION_FAILURE';

export const STRIPE_SUBSCRIPTION_STATUS_UPDATE = 'STRIPE_SUBSCRIPTION_STATUS_UPDATE';
