export const USER_PROFILE_IMAGE_UPLOAD_REQUEST =
  'USER_PROFILE_IMAGE_UPLOAD_REQUEST';
export const USER_PROFILE_IMAGE_UPLOAD_SUCCESS =
  'USER_PROFILE_IMAGE_UPLOAD_SUCCESS';
export const USER_PROFILE_IMAGE_UPLOAD_FAILURE =
  'USER_PROFILE_IMAGE_UPLOAD_FAILURE';

export const PROFILE_IMAGE_UPLOAD_REQUEST = 'PROFILE_IMAGE_UPLOAD_REQUEST';
export const PROFILE_IMAGE_UPLOAD_SUCCESS = 'PROFILE_IMAGE_UPLOAD_SUCCESS';
export const PROFILE_IMAGE_UPLOAD_FAILURE = 'PROFILE_IMAGE_UPLOAD_FAILURE';

// DELETE Profile Images for ProfileImage model
export const PROFILE_IMAGES_DELETE_REQUEST = 'PROFILE_IMAGES_DELETE_REQUEST';
export const PROFILE_IMAGES_DELETE_SUCCESS = 'PROFILE_IMAGES_DELETE_SUCCESS';
export const PROFILE_IMAGES_DELETE_FAILURE = 'PROFILE_IMAGES_DELETE_FAILURE';
