export const USER_REVIEW_LOGIN_REQUEST = 'USER_REVIEW_LOGIN_REQUEST';
export const USER_REVIEW_LOGIN_SUCCESS = 'USER_REVIEW_LOGIN_SUCCESS';
export const USER_REVIEW_LOGIN_FAILURE = 'USER_REVIEW_LOGIN_FAILURE';
export const USER_REVIEW_LOGOUT = 'USER_REVIEW_LOGOUT';

// GET all user Reviewer profiles
export const USER_ADMIN_REVIEWER_DETAILS_REQUEST =
  'USER_ADMIN_REVIEWER_DETAILS_REQUEST';
export const USER_ADMIN_REVIEWER_DETAILS_SUCCESS =
  'USER_ADMIN_REVIEWER_DETAILS_SUCCESS';
export const USER_ADMIN_REVIEWER_DETAILS_FAILURE =
  'USER_ADMIN_REVIEWER_DETAILS_FAILURE';
export const USER_ADMIN_REVIEWER_DETAILS_RESET =
  'USER_ADMIN_REVIEWER_DETAILS_RESET';

// GET all user Reviewer profiles public to send email
export const USER_REVIEWER_DETAILS_REQUEST = 'USER_REVIEWER_DETAILS_REQUEST';
export const USER_REVIEWER_DETAILS_SUCCESS = 'USER_REVIEWER_DETAILS_SUCCESS';
export const USER_REVIEWER_DETAILS_FAILURE = 'USER_REVIEWER_DETAILS_FAILURE';

// Delete reviewer admin
export const USER_ADMIN_DELETE_REQUEST = 'USER_ADMIN_DELETE_REQUEST';
export const USER_ADMIN_DELETE_SUCCESS = 'USER_ADMIN_DELETE_SUCCESS';
export const USER_ADMIN_DELETE_FAILURE = 'USER_ADMIN_DELETE_FAILURE';

export const USER_REVIEWER_REGISTER_REQUEST = 'USER_REVIEWER_REGISTER_REQUEST';
export const USER_REVIEWER_REGISTER_SUCCESS = 'USER_REVIEWER_REGISTER_SUCCESS';
export const USER_REVIEWER_REGISTER_FAILURE = 'USER_REVIEWER_REGISTER_FAILURE';

export const USER_REVIEW_ID_REQUEST = 'USER_REVIEW_ID_REQUEST';
export const USER_REVIEW_ID_SUCCESS = 'USER_REVIEW_ID_SUCCESS';
export const USER_REVIEW_ID_FAILURE = 'USER_REVIEW_ID_FAILURE';

export const USER_REVIEW_CREATE_COMMENT_REQUEST =
  'USER_REVIEW_CREATE_COMMENT_REQUEST';
export const USER_REVIEW_CREATE_COMMENT_SUCCESS =
  'USER_REVIEW_CREATE_COMMENT_SUCCESS';
export const USER_REVIEW_CREATE_COMMENT_FAILURE =
  'USER_REVIEW_CREATE_COMMENT_FAILURE';
export const USER_REVIEW_CREATE_COMMENT_RESET =
  'USER_REVIEW_CREATE_COMMENT_RESET';
