export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';

// Get ALL USERS details
export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAILURE = 'USERS_FAILURE';
export const USERS_RESET = 'USERS_RESET';

// Get user details
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAILURE = 'USER_DETAILS_FAILURE';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

// Get Single user full-Profile by ID
export const USER_FULL_DETAILS_BY_ID_REQUEST =
  'USER_FULL_DETAILS_BY_ID_REQUEST';
export const USER_FULL_DETAILS_BY_ID_SUCCESS =
  'USER_FULL_DETAILS_BY_ID_SUCCESS';
export const USER_FULL_DETAILS_BY_ID_FAILURE =
  'USER_FULL_DETAILS_BY_ID_FAILURE';
export const USER_FULL_DETAILS_BY_ID_RESET = 'USER_FULL_DETAILS_BY_ID_RESET';

//Update user
export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAILURE = 'USER_UPDATE_PROFILE_FAILURE';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

//Delete user
export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAILURE = 'USER_DELETE_FAILURE';
export const USER_DELETE_RESET = 'USER_DELETE_RESET';

// Make or remove as admin
export const USER_ADD_REMOVE_ADMIN_REQUEST = 'USER_ADD_REMOVE_ADMIN_REQUEST';
export const USER_ADD_REMOVE_ADMIN_SUCCESS = 'USER_ADD_REMOVE_ADMIN_SUCCESS';
export const USER_ADD_REMOVE_ADMIN_FAILURE = 'USER_ADD_REMOVE_ADMIN_FAILURE';

// Request new password if forgotten
export const USER_FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST';
export const USER_FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS';
export const USER_FORGOT_PASSWORD_FAILURE = 'USER_FORGOT_PASSWORD_FAILURE';

// UPDATE new password if forgotten
export const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST';
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS';
export const USER_UPDATE_PASSWORD_FAILURE = 'USER_UPDATE_PASSWORD_FAILURE';
